### ISSUE TITLE
Automated testing of algoliasearch-client-python-async on new releases

### ISSUE THREAD

**Issue by PLNech** [algolia/algoliasearch-client-python#309]
It would be great to automatically run the testsuite of [algolia/algoliasearch-client-python-async](https://github.com/algolia/algoliasearch-client-python-async) when we release a new version: this would have avoided the [recent issue](https://github.com/algolia/algoliasearch-client-python/pull/301#issuecomment-341087416) that followed #301.

**Comment by nunomaduro** [comment]
Thansk for creating this issue @PLNech.

The `algolia/algoliasearch-client-python-async` will be depracated, since our API Client v2 supports both synchronous and asynchronous code in the same API client.

Thanks for this proposal, please fell free to ask me to re-open the issue if you think that something should be discussed.
