### ISSUE TITLE
requests[security] and the C tool chain

### ISSUE THREAD

**Issue by ewdurbin** [algolia/algoliasearch-client-python#333]
Hello!

Algolia has been super fun to learn and start working with.

I had one minor concern regarding the pinned dependency on `requests[security]`.

We're using the client with AWS Lambda which makes C Dependencies a _major_ pain in the butt.

Specifying the security extras on your package is an _excellent_ idea, as it ensures that folks with older/out-of-date Python installations get a nice high quality TLS connection to your servers.

For folks running Modern Pythons™️ this is no longer necessary.

And unfortunately for folks running in AWS Lambda or other environments that make deploying pure python modules/dependencies easy, it's just a pain in the butt to add PyOpenSSL, cffi, and cyptography.

You could consider using [PEP 508](https://www.python.org/dev/peps/pep-0508/) [Environment Markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) to specify `requests[security]` for ancient Pythons, while letting folks running the good stuff skate away into the server less sunset :)

**Comment by ercolanelli-leo** [comment]
Hi there,

Thanks for the feedback!
As it turns out, `requests` itself is not compatible with the python versions that would have needed the flair, I just removed it.

The PR is here https://github.com/algolia/algoliasearch-client-python/pull/335
I am just waiting for the reviewers to mark it as valid, and I will release a new version.

Thanks again!

**Comment by julienbourdeau** [comment]
I believe this was fixed by [v1.15.3](https://github.com/algolia/algoliasearch-client-python/releases/tag/1.15.3).
