### ISSUE TITLE
createIfNotExists param ignored in batch mode

### ISSUE THREAD

**Issue by noclat** [algolia/algoliasearch-client-python#338]
From the support: `?createIfNotExists=false` parameter is ignored by the REST API in batch mode. It works well in non-batch mode.

> The python client lib has another bug, passing the fixed '/batch' url instead of the calculated path variable. See here: https://github.com/algolia/algoliasearch-client-python/blob/master/algoliasearch/index.py#L1025 
> (Most probably istead of appending it to the path, probably you should pass it in the params keyword argument).

**Comment by axt** [comment]
Hi, I've reported the bug. 

Just wanted to point out, that based on my experiments, the bug is both present in the REST interface and in the python client lib, so just fixing the python lib will not solve the problem.

**Comment by aGallea** [comment]
I'm having the same problem (using client-scala) - any updates about this bug? can you send link to the bug so we could track?

**Comment by julienbourdeau** [comment]
`createIfNotExists` cannot be passed in the URL parameters of a batch, it will be ignored. This parameters only exists for `partialUpdates`, no other actions.

The method parameters shouldn't be there, I don't know why it was done this way. There are 2 differents actions depending if you want to create a new record or not:
 * `partialUpdateObject`
 * `partialUpdateObjectNoCreate`
https://www.algolia.com/doc/rest-api/search/#batch-write-operations

If you want to meant to use createIfNotExists with `addObjects` or `updateObjects`, it's not possible. The only different with the 2 is that if you call updateObject without objectID it will fail, while addObjects will generate a unique ObjectID for you. Both will create a new record or update existing ones.

Note that it's highly recommened to use `updateObject` over `addObjects` and set the ObjectID yourself, because you often need this id for other operations.

The method param won't be removed in this version, but in the new major version coming up.
