### ISSUE TITLE
Consider dropping Python 3.4

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-python#448]
We've been currently investigating a Travis build issue with Python 3.4 and `stestr` (one of our dev dependencies). We've managed to fix the issue by using a non-breaking version of the dependency (`<2.5.0`) in this commit https://github.com/algolia/algoliasearch-client-python/commit/d719c7a703ce7daf5fb0d4c91b0615767e1e4941. We've also [reported the issue to `stestr`](https://github.com/mtreinish/stestr/issues/264).

However, perhaps the issue can also simply be avoided by stopping to test against Python 3.4 which is a deprecated Python version since March 2019 as per [PEP-429](https://www.python.org/dev/peps/pep-0429/).

WDYT @nunomaduro @Ant-hem @chloelbn?

On my end, I would deprecate Python 3.4 to follow the community but also because migrating between Python 3 minor versions is relatively painless.

**Comment by nunomaduro** [comment]
Thanks for reporting this issue,  today, unless there is a serious reason for it, I don't think we should consider this. Maybe one day, with a new major we may consider that.

Here is the fix for the CI problem: https://github.com/algolia/algoliasearch-client-python/commit/9aa6eca12bda8a51557d7f9e86dc69e3cac24661.

Please re-open the issue if you think that this needs to be re-discussed.
